### ISSUE TITLE
check_a_mundo: shcu_physics == 5

### ISSUE THREAD

**Issue by davegill** [wrf-model/WRF#1042]
From Pedro Jimenez - add these two tests in check_a_mundo:

1. IF ( ( icloud_bl == 1 ) .AND. ( shcu_physics == 5 ) ) THEN STOP
2. IF ( ( icloud     == 3 ) .AND. ( shcu_physics == 5 ) ) THEN STOP

**Comment by pedro-jm** [comment]
@davegill 

I have seen that point 2 has been corrected. Thanks.

We still need to address point 1. This is important because icloud_bl by default is 1. If the user selects Deng shcu, shcu_physics == 5, we have a conflict since it is hard to guess that icloud_bl should be also set to 0. The model will run without any complain.

Thanks.
