### ISSUE TITLE
namelist_defines.inc not found

### ISSUE THREAD

**Issue by jcwarner-usgs** [wrf-model/WRF#1157]
Dear All-
just downloaded the latest version of WRF v5.1.5  from the github link.  I am trying to compile but getting an error:

  ../frame/module_dm.G  > ../frame/module_dm.bb
[[01[[K../frame/module_dm.G:1793:0:^[[m^[[K ^[[01;31m^[[K
fatal error: [[[[Knamelist_defines.inc: No such file\  or directory
 #include "namelist_defines.inc"

It cant find the file called namelist_defines.inc. is that file to be created during the build in calls to gen_config.c?
WRF/tools/registry.c:254:  gen_namelist_defines ( "inc", 0 ) ;  /* without dimension statements  */
WRF/tools/registry.c:255:  gen_namelist_defines ( "inc", 1 ) ;  /* with dimension statements     */
WRF/tools/gen_config.c:14:gen_namelist_defines ( char * dirname , int sw_dimension )
WRF/tools/gen_config.c:21:  sprintf( fn, "namelist_defines%s.inc", sw_dimension?"":"2" ) 

any suggestions appreciated.
-john

**Comment by davegill** [comment]
@jcwarner-usgs 
John,
I just used the following
```
git clone https://github.com/wrf-model/WRF
cd WRF
git checkout release-v4.1.5
```
With GNU 9, I then built and ran our entire regression suite (about 150 short simulations) successfully. This used `configure -d` to allow bit-wise comparisons with varying numbers of processors. The tests included ARW, NMM, Chemistry, idealized, real-data, 3d and 2d, moving nests. Most tests do serial, openmp, and mpi. There tests cover a large portion of the available physics options, and significant WRF features: vertical nesting, digital filtering, adaptive time stepping, fdda, nesting, etc.

Because I cannot replicate your error condition, we will need back and forth communications and that is best handled on our WRF forum. Can you please repost this on the WRF forum: forum.mmm.ucar.edu

Dave

**Comment by jcwarner-usgs** [comment]
Is that all you got?  "about 150 short simulations"?  (ha - just kidding)
Thanks for the quick look.  i think it is me.  Something with the coupling did not complete a file, and then it cascaded in the build. i am digging in deeper, but you can close this ticket. thanks!!
