### ISSUE TITLE
Regional timestep

### ISSUE THREAD

**Issue by nbald** [wrf-model/WRF#1237]
Hi

In the case of large domain, I often see a small part of the domain driving the timestep down, while the CFL conditions are met everywhere else.

How feasible would it be to have different timesteps across the domain?
Any advice on where to begin?

**Comment by nbald** [comment]
I think it is similar to Hierarchical Time Stepping in the CPAS model (proprietary MPAS fork) https://cpas.earth/technology/about

**Comment by davegill** [comment]
@nbald 
Nicolas,
This is the correct place for requesting a new feature to the code. However, if you would like some advice about domain setups, nesting, adaptive time stepping, filters, w_damping (all capabilities that can remove allow an increase in time step), post a question on the WRF Forum (forum.mmm.ucar.edu).

**Comment by nbald** [comment]
Hi
I am talking about a new feature addition to the code

**Comment by davegill** [comment]
@nbald 
Nicolas,
Go ahead and post you proposed ideas here, and then we can all iterate. This development work for a new feature would start with the WRF develop branch, but that is getting ahead of ourselves a bit.

If part of the domain is using a smaller time step, then the rest of the domain is waiting for the slow part of the domain to complete. How is this an advantage over the whole domain running slowly?

**Comment by nbald** [comment]
To avoid the wait, I was thinking about leveraging the tiling process.
In my case, the "stressed" regions are always the same. We could imagine statically assign smaller tiles to those regions. Double the timestep but half the surface compared to the other tiles. How realistic is that?

**Comment by davegill** [comment]
@nbald 
There are likely to be some inconsistencies in the dynamics and physics. The first step might be to look at the domain decomposition code to see if that can be modified to permit this generalized decomposition. All of the automatically generated code for communication and feedback assume a known layout. The high-order schemes assume availability of data  at known indexes. This could be a challenge.

Since MPAS has a regional domain capability, and MPAS has an unstructured layout of the grid cells, and you said that this was only available in a proprietary version of MPAS - why not look at including this option in that model?
