### ISSUE TITLE
Where to find user guide for WRF4.2?

### ISSUE THREAD

**Issue by mcjason413** [wrf-model/WRF#1279]
I can only find the version for WRF3.9 online. Does the user guide update with the model version?

**Comment by davegill** [comment]
@mcjason413 
We are in the process of getting our documentation organized.
1. Take a look at https://www2.mmm.ucar.edu/wrf/users/tutorial/tutorial_presentation_winter_2020.htm
2. Would you please post this questionin the WRF User's Forum, under "Miscellaneous/General Questions": https://forum.mmm.ucar.edu/
3. Also, please post the response so that others can find it. The syntax is a 4-digit year, and either string "summer" or "winter".
I am closing this issue.

**Comment by mcjason413** [comment]
Thank you, I will
