### ISSUE TITLE
Problem with AOCC Compilers

### ISSUE THREAD

**Issue by kasrash** [wrf-model/WRF#1679]
Dear WRF Community,

Hope this is not off-topic. I am trying to compile WRF with AOCC compilers as I have seen WRF performs better with these compilers on AMD processors. Since AOCC is not natively supported, I tried GNU and Intel configurations to compile, but as expected, it fails. 
I am wondering if there is a fix or a way to compile WRF with AOCC compilers.

Thank you so much for your time and response in advance.

**Comment by mgduda** [comment]
This might be a question better suited to the WRF forum at https://forum.mmm.ucar.edu . There's a section of the forum for questions about compilation and/or installation: https://forum.mmm.ucar.edu/phpBB3/viewforum.php?f=37 .

Generally, we use GitHub Issues to report and track code bugs or other issues rather than to provide support.
