### ISSUE TITLE
Issues in modules phys/module_cu_g3.F, phys/module_cu_gd.F and phys/module_cu_gf_deep.F

### ISSUE THREAD

**Issue by mirekand** [wrf-model/WRF#2114]
**Describe the bug**
There are variables used before set in phys/module_cu_g3.F, phys/module_cu_gd.F and phys/module_cu_gf_deep.F

**To Reproduce**
In phys/module_cu_g3.F, phys/module_cu_gd.F and module_cu_gf_deep.F (_SUBROUTINE cup_env_)
In line:
`z(i,k)=(he(i,k)-1004.*t(i,k)-2.5e6*q(i,k))/9.81`
**he**() is used before values are assigned to this variable.

In addition in (SUBROUTINE cup_dd_aa0) in module_cu_gd.F
**AA0** is used before its values are set (to 0 probably). I'm assuming **AA0** should be set in this routine, given it has intent (out) attribute, rather than just accumulated. 

**Expected behavior**
values for array **he** should be calculated before used. And **AA0**  set to some value (0?) before used in the only loop in this routine (it's also possible that values for AA0 are accumulated but then it should be intent(inout)).

**Comment by weiwangncar** [comment]
@mirekand Thanks for the notes. For the first issue, can you try to change the declaration for variable in subroutine cup_env from 'out' to 'inout' - it looks like just before the subroutine is called, the variable is set in the routine which calls cup_env. As for the second issue, it looks like all calls to cup_dd_aa0 are commented out. If your compiler is complaining about it, you can make a value so that it can pass.

**Comment by mirekand** [comment]
@weiwangncar thanks for looking into this issue. I'll make changes you recommended.
