### ISSUE TITLE
run wrf.exe error：WRF initialization routines

### ISSUE THREAD

**Issue by xigrug** [wrf-model/WRF#659]
---- ERROR: The input file appears to be from a pre-v4 version of WRF initialization routines. I use the WPS-4.0.1, using netcdf=3.6.3.

**Comment by davegill** [comment]
@xigrug @kkeene44 @smileMchen 

This diagnostic output line that you received is part of a feature that was introduced into the WRF model to allow older data sets (pre v4) to be used by the WRF model after the large change from version 3 to version 4.

The full error message probably looked like the following:

```
File name that is causing troubles = _your_actual_file_name_here_
You can try 
1) ensure that the input file was created with WRF v4 pre-processors, or  
2) use force_use_old_data=T in the time_control record of the namelist.input file
---- ERROR: The input file appears to be from a pre-v4 version of WRF initialization routines
```

Please include the entire error message in your edit of this issue so that we know what the offending data set / filename is. For example, look at issue #600 which found that the obsgrid program was not supported in version 4. If you have identified another data that should work with v4 (and does not), we need to know that information.

However, if the solution is to put `use_old_data=.true.` in the namelist, then this issue does not really belong here, but in the forum instead. For example, this would be the case if part of the input stream came from the older v3 WRF system (metgrid, real, etc.)

If this problem correctly belongs in the forum, please go to: 
```
http://forum.mmm.ucar.edu/phpBB3
```

If posting this issue on the forum, remember to also upload your namelist.input file.

**Comment by davegill** [comment]
@xigrug @smileMchen @kkeene44 
This should be moved to the forum. That venue allows for a back-and-forth debugging discussion and an easy way to collect necessary files, such as namelist.input. What needs to be uncovered is what file is actually causing the trouble.

Please post this problem on the forum.
Upload your namelist.input file
Upload your printout file from wrf.exe. For example, upload the rsl*0000 files, or the combined error and standard out files from the serial WRF model.
There is a nextcloud capability to also upload your wrfinput and wrfbdy files.

Provide information on the forum about what you are doing with additional input files: sst update, fdda, chemistry, etc. Is this nested? Does it stop on d01? 

No need to comment here further, I am going to close this issue soon.

**Comment by davegill** [comment]
Pushed discussion over to forum

**Comment by melisadr** [comment]
Hello David, I run WPSv4.0 compiled with netcdflibversion=4.6.1|hdf5libversion=1.10.1 with FNL (Vtable.GFS, GEOGRID.AWR_CHEM), the TITLE of the OUTPUT is OUTPUT FROM METGRID V4.0 but when I run wrf:
d01 2015-08-15_00:00:00  2) use force_use_old_data=T in the time_control record of the namelist.input file
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     324
 ---- ERROR: The input file appears to be from a pre-v4 version of WRF initialization routines

when I set force_use_old_data=T
Timing for Writing wrfout_d01_2015-08-15_00:00:00 for domain        1:    2.52302 elapsed seconds
d01 2015-08-15_00:00:00  Error trying to read metadata

Is this also o problem for the forum or I have to report it here?
Thanks in advance,
Melisa

**Comment by davegill** [comment]
@melisadr 
Melisa,
This should definitely be directed to the forum. The forum format allows us to go back and forth on getting namelist information, and possibly your metgrid files. Please include your namelist.input file in the attachments when this is reposted on the forum.
Dave

**Comment by davegill** [comment]
@melisadr 
Melisa,
If this is a WRF Chem build and run, we will want to know that on the forum also.
