### ISSUE TITLE
Restart runs not reproducible in nest when topo_shading is turned on

### ISSUE THREAD

**Issue by emilycollier** [wrf-model/WRF#922]
Summary: Restart runs in a nest are not reproducible when topo_shading is turned on, because shadowmask has a different value after restart compared to the continuous simulation.

Build: WRF 4.1; compiler choice: 66

Bug Fix: Editing Registry.EM_COMMON to add shadowmask to restart files seems to fix the problem.

**Comment by davegill** [comment]
@emilycollier 
Emily,
Would you be interested in putting a pull request together to get this fix into the code? The problem that you have identified seems fairly contained (likely only a change in the Registry, as you mention). 

If so, use the release-v4.1.2 branch as your starting point.

Then do a checkout -b to get to your shadow-fix branch. You can take a look at https://github.com/wrf-model/WRF/wiki/Workflow-for-WRF-Code-Modification for lots more info on the mechanics of the commit specifically for a bug-fix

We will likely iterate with you on the contents of the commit message (partially we iterate since "more eyes" is a good idea, and partially as you are relatively new to our pull request requirements). More info on the way to build a good message is available at https://github.com/wrf-model/WRF/wiki/Making-a-good-pull-request-message.

**Comment by emilycollier** [comment]
@davegill 
Hi Dave,

Sure, I can do that. Note that I had actually tested adding shadowmask & ht_shad to the restart file, and assumed that the former was the fix. I checked, and it is actually ht_shad that makes restarts reproducible, while shadowmask makes no difference.

Emily
